<?php

// File: models/Visit.php
class Visit {
    private $conn;
    private $table_name = "visits";

    public $visit_id;
    public $visitor_id;
    public $host_employee_id;
    public $badge_number;
    public $purpose;
    public $additional_notes;
    public $check_in_time;
    public $check_out_time;
    public $valid_until;
    public $terms_accepted;
    public $photo_consent;

    public function __construct($db) {
        $this->conn = $db;
    }

    // Check in visitor
    public function checkIn() {
        // The badge_number will be auto-generated by the stored procedure
        $query = "INSERT INTO " . $this->table_name . "
                SET
                    visitor_id = :visitor_id,
                    host_employee_id = :host_employee_id,
                    purpose = :purpose,
                    additional_notes = :additional_notes,
                    check_in_time = NOW(),
                    valid_until = DATE_ADD(NOW(), INTERVAL 8 HOUR),
                    terms_accepted = :terms_accepted,
                    photo_consent = :photo_consent";

        $stmt = $this->conn->prepare($query);

        // Sanitize and bind
        $stmt->bindParam(":visitor_id", $this->visitor_id);
        $stmt->bindParam(":host_employee_id", $this->host_employee_id);
        $stmt->bindParam(":purpose", $this->purpose);
        $stmt->bindParam(":additional_notes", $this->additional_notes);
        $stmt->bindParam(":terms_accepted", $this->terms_accepted);
        $stmt->bindParam(":photo_consent", $this->photo_consent);

        if($stmt->execute()) {
            $this->visit_id = $this->conn->lastInsertId();
            
            // Get the generated badge number
            $query = "SELECT badge_number FROM " . $this->table_name . " WHERE visit_id = ?";
            $stmt = $this->conn->prepare($query);
            $stmt->bindParam(1, $this->visit_id);
            $stmt->execute();
            $row = $stmt->fetch(PDO::FETCH_ASSOC);
            $this->badge_number = $row['badge_number'];
            
            return true;
        }
        return false;
    }

    // Check out visitor
    public function checkOut() {
        $query = "UPDATE " . $this->table_name . "
                SET check_out_time = NOW()
                WHERE visit_id = :visit_id";

        $stmt = $this->conn->prepare($query);
        $stmt->bindParam(":visit_id", $this->visit_id);

        if($stmt->execute()) {
            return true;
        }
        return false;
    }

    // Get active visits (using the view)
    public function getActiveVisits() {
        $query = "SELECT * FROM active_visits ORDER BY check_in_time DESC";
        
        $stmt = $this->conn->prepare($query);
        $stmt->execute();
        return $stmt;
    }

    // Get all visits
    public function getAllVisits() {
        $query = "SELECT 
                    v.*,
                    CONCAT(vi.first_name, ' ', vi.last_name) as visitor_name,
                    vi.company as visitor_company,
                    vi.email as visitor_email,
                    e.name as host_name,
                    d.name as department_name
                FROM " . $this->table_name . " v
                JOIN visitors vi ON v.visitor_id = vi.visitor_id
                JOIN employees e ON v.host_employee_id = e.employee_id
                JOIN departments d ON e.department_code = d.department_code
                ORDER BY v.check_in_time DESC";
        
        $stmt = $this->conn->prepare($query);
        $stmt->execute();
        return $stmt;
    }

    // Get visitor history
    public function getVisitorHistory($visitor_id) {
        $query = "SELECT 
                    v.*,
                    e.name as host_name,
                    d.name as department_name
                FROM " . $this->table_name . " v
                JOIN employees e ON v.host_employee_id = e.employee_id
                JOIN departments d ON e.department_code = d.department_code
                WHERE v.visitor_id = :visitor_id
                ORDER BY v.check_in_time DESC";
        
        $stmt = $this->conn->prepare($query);
        $stmt->bindParam(":visitor_id", $visitor_id);
        $stmt->execute();
        return $stmt;
    }
}

